repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: ['--py36-plus']
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.6.2'
    hooks:
      - id: prettier
        types: [file]
        files: \.(js|jsx|ts|tsx|yaml|yml|json|json5)$
        additional_dependencies:
          - prettier
          - '@whtsky/prettier-config'
